services:
  - type: web
    name: telegram-holidays-scraper
    runtime: docker
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: SCRAPER_API_KEY
        sync: false
      - key: SCRAPER_PROXY_SERVER
        sync: false
      - key: SCRAPER_PROXY_USERNAME
        sync: false
      - key: SCRAPER_PROXY_PASSWORD
        sync: false
